  services:
    - type: web
      env: static
      name: shoppershaven-client
      staticPublishPath: client/build
      routes:
        - type: rewrite
          source: /*
          destination: /index.html